comunidadunab/config/routes.rb
Rails.application.routes.draw do
  resources :curso_seccions
  resources :profesor_seccions
  resources :alumno_cursos
        devise_for :users
  #get 'bienvenido/index'
devise_scope :user do

    
    authenticated  do
            root to: 'bienvenido#index'
            end
    unauthenticated do
            root to: 'devise/sessions#new', as: 'unauthenticated_root'
            end
  end
        #root "bienvenido#index"
        resources :mensajes
        resources :foros
        resources :seccions
        resources :cursos
        resources :profesors
        resources :alumnos
 	get "alumnos", to: "alumnos#index"
   	get "mensajes", to: "mensajes#index"
	get "cursos", to: "cursos#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

#devise_scope :users do

            #authenticated  do
            #root to: 'bienvenido#index'
            #end

            #unauthenticated do
            #root to: 'devise/sessions#new', as: 'unauthenticated_root'
            #end

comunidadunab/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

comunidadunab/app/models/alumno.rb
class Alumno   < ApplicationRecord
has_many :alumno_cursos
has_many :cursos, through: :alumno_cursos
end

comunidadunab/app/models/alumno_curso.rb
class AlumnoCurso < ApplicationRecord
belongs_to :alumno
belongs_to :curso
end

comunidadunab/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

comunidadunab/app/models/curso.rb
class Curso < ApplicationRecord
has_many :alumno_cursos
has_many :alumnos, through: :alumno_cursos
has_many :curso_seccions
has_many :seccions, through: :curso_seccions

end

comunidadunab/app/models/curso_seccion.rb
class CursoSeccion < ApplicationRecord
  belongs_to :curso
  belongs_to :seccion
end

comunidadunab/app/models/foro.rb
class Foro < ApplicationRecord

belongs_to :seccion
  has_many :mensajes
end

comunidadunab/app/models/mensaje.rb
class Mensaje < ApplicationRecord
  belongs_to :foro
end

comunidadunab/app/models/profesor.rb
class Profesor < ApplicationRecord
  has_many :profesor_seccions
  has_one :seccion , through: :profesor_seccions


end

comunidadunab/app/models/profesor_seccion.rb
class ProfesorSeccion < ApplicationRecord
  belongs_to :profesor
  belongs_to :seccion
end

comunidadunab/app/models/seccion.rb
class Seccion < ApplicationRecord
has_one :foro
  has_many :profesor_seccions
  has_many :profesors, through: :profesor_seccions
  has_many :curso_seccions
  has_many :cursos, through:  :curso_seccions
end

comunidadunab/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

comunidadunab/app/controllers/curso_seccions_controller.rb
class CursoSeccionsController < ApplicationController
  before_action :set_curso_seccion, only: [:show, :edit, :update, :destroy]

  # GET /curso_seccions
  # GET /curso_seccions.json
  def index
    @curso_seccions = CursoSeccion.all
  end

  # GET /curso_seccions/1
  # GET /curso_seccions/1.json
  def show
  end

  # GET /curso_seccions/new
  def new
    @curso_seccion = CursoSeccion.new
  end

  # GET /curso_seccions/1/edit
  def edit
  end

  # POST /curso_seccions
  # POST /curso_seccions.json
  def create
    @curso_seccion = CursoSeccion.new(curso_seccion_params)

    respond_to do |format|
      if @curso_seccion.save
        format.html { redirect_to @curso_seccion, notice: 'Curso seccion was successfully created.' }
        format.json { render :show, status: :created, location: @curso_seccion }
      else
        format.html { render :new }
        format.json { render json: @curso_seccion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /curso_seccions/1
  # PATCH/PUT /curso_seccions/1.json
  def update
    respond_to do |format|
      if @curso_seccion.update(curso_seccion_params)
        format.html { redirect_to @curso_seccion, notice: 'Curso seccion was successfully updated.' }
        format.json { render :show, status: :ok, location: @curso_seccion }
      else
        format.html { render :edit }
        format.json { render json: @curso_seccion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /curso_seccions/1
  # DELETE /curso_seccions/1.json
  def destroy
    @curso_seccion.destroy
    respond_to do |format|
      format.html { redirect_to curso_seccions_url, notice: 'Curso seccion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curso_seccion
      @curso_seccion = CursoSeccion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def curso_seccion_params
      params.require(:curso_seccion).permit(:curso_id, :seccion_id)
    end
end

comunidadunab/app/controllers/foros_controller.rb
class ForosController < ApplicationController
  before_action :set_foro, only: [:show, :edit, :update, :destroy]

  # GET /foros
  # GET /foros.json
  def index
    @foros = Foro.all
  end

  # GET /foros/1
  # GET /foros/1.json
  def show
  end

  # GET /foros/new
  def new
    @foro = Foro.new
  end

  # GET /foros/1/edit
  def edit
  end

  # POST /foros
  # POST /foros.json
  def create
    @foro = Foro.new(foro_params)

    respond_to do |format|
      if @foro.save
        format.html { redirect_to @foro, notice: 'Foro was successfully created.' }
        format.json { render :show, status: :created, location: @foro }
      else
        format.html { render :new }
        format.json { render json: @foro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foros/1
  # PATCH/PUT /foros/1.json
  def update
    respond_to do |format|
      if @foro.update(foro_params)
        format.html { redirect_to @foro, notice: 'Foro was successfully updated.' }
        format.json { render :show, status: :ok, location: @foro }
      else
        format.html { render :edit }
        format.json { render json: @foro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foros/1
  # DELETE /foros/1.json
  def destroy
    @foro.destroy
    respond_to do |format|
      format.html { redirect_to foros_url, notice: 'Foro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foro
      @foro = Foro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foro_params
      params.require(:foro).permit(:id, :anuncio, :foro)
    end
end

comunidadunab/app/helpers/alumnos_helper.rb
module AlumnosHelper
end

comunidadunab/app/helpers/application_helper.rb
module ApplicationHelper
end

comunidadunab/app/helpers/bienvenido_helper.rb
module BienvenidoHelper
end

comunidadunab/app/helpers/curso_seccions_helper.rb
module CursoSeccionsHelper
end

comunidadunab/app/helpers/cursos_helper.rb
module CursosHelper
end

comunidadunab/app/helpers/foros_helper.rb
module ForosHelper
end

comunidadunab/app/helpers/mensajes_helper.rb
module MensajesHelper
end

comunidadunab/app/helpers/profesors_helper.rb
module ProfesorsHelper
end

comunidadunab/app/helpers/seccions_helper.rb
module SeccionsHelper
end

comunidadunab/app/views/curso_seccions/_form.html.erb
<%= form_with(model: curso_seccion, local: true) do |form| %>
  <% if curso_seccion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(curso_seccion.errors.count, "error") %> prohibited this curso_seccion from being saved:</h2>

      <ul>
        <% curso_seccion.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :curso_id %>
    <%= form.number_field :curso_id %>
  </div>

  <div class="field">
    <%= form.label :seccion_id %>
    <%= form.number_field :seccion_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

comunidadunab/app/views/curso_seccions/edit.html.erb
<h1>Editing Curso Seccion</h1>

<%= render 'form', curso_seccion: @curso_seccion %>

<%= link_to 'Show', @curso_seccion %> |
<%= link_to 'Back', curso_seccions_path %>

comunidadunab/app/views/curso_seccions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Curso Seccions</h1>

<table>
  <thead>
    <tr>
      <th>Curso</th>
      <th>Seccion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @curso_seccions.each do |curso_seccion| %>
      <tr>
        <td><%= curso_seccion.curso_id %></td>
        <td><%= curso_seccion.seccion_id %></td>
        <td><%= link_to 'Show', curso_seccion %></td>
        <td><%= link_to 'Edit', edit_curso_seccion_path(curso_seccion) %></td>
        <td><%= link_to 'Destroy', curso_seccion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Curso Seccion', new_curso_seccion_path %>

comunidadunab/app/views/curso_seccions/new.html.erb
<h1>New Curso Seccion</h1>

<%= render 'form', curso_seccion: @curso_seccion %>

<%= link_to 'Back', curso_seccions_path %>

comunidadunab/app/views/curso_seccions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Curso:</strong>
  <%= @curso_seccion.curso_id %>
</p>

<p>
  <strong>Seccion:</strong>
  <%= @curso_seccion.seccion_id %>
</p>

<%= link_to 'Edit', edit_curso_seccion_path(@curso_seccion) %> |
<%= link_to 'Back', curso_seccions_path %>